// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrguqrperpqlaayuvipc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZ3VxcnBlcnBxbGFheXV2aXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjkzMzIsImV4cCI6MjA1ODA0NTMzMn0.lqNo0Wz2m9qtmcVq3kolNWM2AwXgnRiFQnAw0ezyu4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);